### ISSUE TITLE
Cannot open ref file

### ISSUE THREAD

**Issue by huidongchen** [cxzhu/Paired-seq#2]
Hi,

I am running into errors `Cannot open ref file` when executing the last step `reachtools bam2Mtx CZ${s}_mm10.bam mm10_1kb` in `proc_DNA.sh`.

It seems currently the ref file is hard-coded in `main.cpp` https://github.com/cxzhu/Paired-seq/blob/master/ReachTools/main.cpp#L120

```cpp
else if(ref == "mm10_1k"){
     ref = "/projects/ps-renlab/chz272/genome_ref/mm10.bin1k.txt";
```
What would you suggest I do to get rid of this error and where can I find this file? 

Thanks!

**Comment by cxzhu** [comment]
@huidongchen 
You can download the ref file from: http://renlab.sdsc.edu/chz272/mm10.bin1k.txt. Or you can customize a ref file in the same format. And then reachtools bam2Mtx input.bam path_to_your_ref_file to generate the matrix.

**Comment by huidongchen** [comment]
Thanks so much for your prompt reply! This is incredibly helpful!
