### ISSUE TITLE
Lacking source files of function bam2Mtx

### ISSUE THREAD

**Issue by lfn17** [cxzhu/Paired-seq#3]
Hi Chenxu,

I notice the function of bam2Mtx in the reachtools package need a ref parameter (reachtools Bam2Mtx in.bam/in.sam [ref], ref is optional for RNA-seq but mandatory for ATAC-seq) However in the main.cpp, the ref parameter point to private files (such as mm10_1kb, does it mean a 1kb bed file for mm10 genome?) which are not available for custom users. Could you please provide a header in the instruction if you are convenient？ Thanks a lot!

Best, 
Fangnong

**Comment by lfn17** [comment]
I notice the same question of issues 2, that is extremely helpful.

**Comment by cxzhu** [comment]
> I notice the same question of issues 2, that is extremely helpful.

Hi Fangnong @lfn17 

The ref files are required for both DNA and RNA, here the DNA ref are 1kb-binned file and RNA ref are ensemble genes.
The header for the reference file should be:

DNA
chrom pos_start pos_end bin_name_1 bin_name_2
chr1	0	1000	chr1:0-1000 chr1:0-1000
chr1	1000	2000	chr1:1000-2000 chr1:1000-2000

RNA
chrom pos_start pos_end gene_ID gene_symbol
chr1	3072253	3075322	ENSMUSG00000102693 4933401J01Rik
chr1	3101016	3103125	ENSMUSG00000064842 Gm26206

I have added this header annotation into the source code to make it clearer to other readers. Thank you for your suggestion!

Best,
Chenxu
