### ISSUE TITLE
SRR8980188 full barcoded reads low.

### ISSUE THREAD

**Issue by macros29** [cxzhu/Paired-seq#5]
Hi Chenxu,

I downloaded the dataset from SRA and run reachtools combine2 on R1 and R2, but the full barcoded reads were reported at only 0.02%. Is that normal?

Best,
Zhen

**Comment by cxzhu** [comment]
Hi @macros29,

The SRR8980188 is a four-level barcoding library (Paired-seq V1), please use: https://github.com/cxzhu/Paired-seq/blob/master/proc_DNA.sh to process.

Best,
Chenxu

**Comment by macros29** [comment]
Ah, I was looking at the wrong pipeline. Thanks for the response!
