### ISSUE TITLE
maker gene of the cerebral cortex cells data

### ISSUE THREAD

**Issue by cynthier** [cxzhu/Paired-seq#7]
Dear author,

Thanks for your awesome work. After reading your paper, I want to know more about the maker gene of the cerebral cortex cells data, but I cannot find this file on github. Maybe I miss it carelessly, and could you please tell me where it was placed or upload it?

**Comment by cxzhu** [comment]
Hi @cynthier,

We didn't do differential analysis for genes across clusters in this study. If you are looking for information outside our figures, you can download our source data to do additional analysis. Sorry for cannot provide further help.
