### ISSUE TITLE
Cannot visualize data properly by Seurat and Signac

### ISSUE THREAD

**Issue by Telogen** [cxzhu/Paired-seq#8]
Hi, Dr. Zhu,
I'm processing the RNA part of Paired-seq data using  Seurat following these codes
```
counts <- Read10X('./data/Adult_Cerebrail_Cortex/Adult_CTX_RNA/')
metadata <- read.csv('./data/Adult_Cerebrail_Cortex/Cell_embeddings.csv')
rownames(metadata) <- metadata$ID
metadata <- metadata[colnames(RNA),]
RNA$batch <- metadata$Rep
RNA$cluster <- metadata$Cluster
RNA$true <- as.character(factor(metadata$Cluster,labels = c('AS','MG','OC','Ex1','Ex2','Ex3','In1','In2','In3')))
RNA <- NormalizeData(RNA)
RNA <- FindVariableFeatures(RNA)
LabelPoints(plot = VariableFeaturePlot(RNA), points = head(VariableFeatures(RNA), 10), repel = TRUE)
RNA <- ScaleData(RNA)
RNA <- RunPCA(RNA)
RNA <- RunUMAP(RNA, dims = 1:20)
DimPlot(RNA, group.by = "true", label = TRUE) + NoLegend()
```
But I got this strange UMAP output of the RNA data
![image](https://user-images.githubusercontent.com/54151359/170992586-7ca7a577-ce48-445b-b97a-537d093364ba.png)

Similarly, I process the ATAC part of Paired-seq data using  Signac following these codes
```
counts <- Read10X("./data/Adult_Cerebrail_Cortex/Adult_CTX_DNA/")
chrom_assay <- CreateChromatinAssay(counts,sep = c(":", "-"))
ATAC <- CreateSeuratObject(chrom_assay,assay = "ATAC")
ATAC <- RunTFIDF(ATAC)
ATAC <- FindTopFeatures(ATAC, min.cutoff = 'q0')
ATAC <- RunSVD(ATAC)
DepthCor(ATAC,n = 50)
ATAC <- RunUMAP(ATAC, dims = 2:30, reduction = 'lsi')
metadata <- read.csv('./data/Adult_Cerebrail_Cortex/Cell_embeddings.csv')
rownames(metadata) <- metadata$ID
metadata <- metadata[colnames(ATAC),]
ATAC$batch <- metadata$Rep
ATAC$cluster <- metadata$Cluster
ATAC$true <- as.character(factor(metadata$Cluster, labels = c('AS','MG','OC','Ex1','Ex2','Ex3','In1','In2','In3')))
DimPlot(object = ATAC, label = T,group.by = 'true') + NoLegend()
```
And I got this 
![image](https://user-images.githubusercontent.com/54151359/170993531-8308f79d-f666-4ffa-9d19-0514b4d7d2cb.png)

Could you please give me some suggestions on how to deal with Pair-seq data in a proper way? Many thanks!

**Comment by cxzhu** [comment]
Hi @Telogen,

Thank you for your interest in our data. We used snapATAC to process the data, please refer to https://github.com/cxzhu/Paired-seq/blob/master/snapATAC_RNA.R and https://github.com/cxzhu/Paired-seq/blob/master/snapATAC_DNA.R, which is designed for lower-coverage datasets.

You can also find our latest data with higher coverage, which should be more compatible with the current Seurat and Signac, from https://ftp.ncbi.nlm.nih.gov/geo/series/GSE152nnn/GSE152020/suppl/GSE152020_Paired-Tag_RNA_filtered_matrix.tar.gz and https://ftp.ncbi.nlm.nih.gov/geo/series/GSE152nnn/GSE152020/suppl/GSE152020_Paired-seq_DNA_filtered_matrix.tar.gz

Best,
Chenxu

**Comment by Telogen** [comment]
Thanks Dr. Zhu! I'll try it.
